spring:
  redis:
    host: localhost
    password:
    database: 0
    port: 6379

sso:
  loginUrl: http://127.0.0.1:3000/login
  logoutUrl: http://127.0.0.1:3000/logout

context:
  commonstatic:
  projectstatic: